name: Lint

on:
  - push
  - pull_request

jobs:
  build:
    name: Lint on Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-20.04

    if: github.event_name != 'pull_request' || github.repository_owner != github.actor

    strategy:
      matrix:
        ruby:
          - '2.7'
          - '2.6'
          - '2.5'

    steps:
      - name: Checkout Reposity
        uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Run RuboCop Linter
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake rubocop
